[customizations.installer.kickstart]
contents = """
# Installation Display Mode
graphical

# EULA
eula --agreed 

# Keyboard Layout
keyboard --vckeymap=latam --xlayouts='latam'

# System language
lang es_MX.UTF-8

# TimeZone
timezone America/Mexico_City

# Disk partitioning
## Destroy all disks
zerombr
## Disk used by installation program
ignoredisk --only-use=vda,vdb
## Cleaning disks
clearpart --all --initlabel --drives=vda,vdb
## Partitions
part /boot/efi --fstype="efi" --ondisk=vda --size=600 --fsoptions="umask=0077,shortname=winnt"
part /boot --fstype="xfs" --ondisk=vda --size=1024
part / --fstype="xfs" --ondisk=vda --grow
part /var/home --fstype="xfs" --ondisk=vdb --grow

# Network config
network --bootproto=dhcp --hostname USERNAME-virtual-desktop.linuxero-agrio.com.mx 

# Admin User
user --groups=wheel --name=admin --password=ADMINPASS --plain --gecos="Admin User"
sshkey --username admin "ADMINSSHPUBKEY"

# Regular user
user --groups=kasmvnc-cert --name=USERNAME --password=USERPASS --plain --gecos="COMPLETEUSERNAME"
sshkey --username USERNAME "ADMINSSHPUBKEY"

# Poweroff when finish
poweroff

%post --erroronfail --log /var/roothome/post-config.log

# Set multi-user default target
systemctl set-default multi-user.target

%end

"""

[customizations.installer.modules]
enable = [
  "org.fedoraproject.Anaconda.Modules.Localization",
  "org.fedoraproject.Anaconda.Modules.Network",
  "org.fedoraproject.Anaconda.Modules.Payloads",
  "org.fedoraproject.Anaconda.Modules.Runtime",
  "org.fedoraproject.Anaconda.Modules.Security",
  "org.fedoraproject.Anaconda.Modules.Services",
  "org.fedoraproject.Anaconda.Modules.Storage",
  "org.fedoraproject.Anaconda.Modules.Subscription",
  "org.fedoraproject.Anaconda.Modules.Timezone",
  "org.fedoraproject.Anaconda.Modules.Users"
]
