apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vm-pipelines-pipeline-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: vm-pipelines