apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-projects
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: patch-me-see-overlays
    repoURL: https://github.com/linuxeroagrio/vm-pipeline.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true