apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-virtual-desktop-rootdisk-pvc
spec:
  accessModes:
  - {{ .Values.storage.rootdisk.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.storage.rootdisk.capacity | default "30Gi" }}
  storageClassName: {{ .Values.storage.rootdisk.storageClass | default "lvms-vg1" }}