apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-virtual-desktop-homedisk-pvc
spec:
  accessModes:
  - {{ .Values.storage.homedisk.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.storage.homedisk.capacity | default "20Gi" }}
  storageClassName: {{ .Values.storage.homedisk.storageClass | default "lvms-vg1" }}