apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: {{ .Release.Name }}-virtualdesktop
spec:
  runStrategy: {{ .Values.virtualMachineResources.runStrategy | default "Manual" }}
  template:
    metadata:
      labels: 
        remote-desktop-user: {{ .Release.Name }}
    spec:   
      domain: 
        cpu:
          cores: 1
          threads: 1
          sockets: {{ .Values.virtualMachineResources.cpu | default "2" }}
        firmware:
          bootloader:
            efi:
              secureBoot: false
        devices:
          disks:  
          - bootOrder: 1
            name: rootdisk
            disk:
              bus: virtio
          - bootOrder: 2
            name: homedisk
            disk:
              bus: virtio
          - bootOrder: 3
            name: cdrom-custom-iso
            cdrom:
              bus: sata
              readonly: true
              tray: {{ .Values.virtualMachineResources.cdrom.tray | default "closed" }}
          interfaces:
          - masquerade: {}
            model: virtio
            name: default 
        resources:
          requests:
            memory: {{ .Values.virtualMachineResources.memory | default "4Gi" }}
          limits:
            memory: {{ .Values.virtualMachineResources.memory | default "4Gi" }}
      networks:
      - name: default 
        pod: {} 
      terminationGracePeriodSeconds: 180
      volumes:
      - name: rootdisk
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-virtual-desktop-rootdisk-pvc
      - name: homedisk
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-virtual-desktop-homedisk-pvc
      - name: cdrom-custom-iso
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-virtual-desktop-iso-pvc
