apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-vnc
spec:
  ports:
  - name: {{ .Values.service.name | default "vnc" }}
    port: {{ .Values.service.port | default 8444 }}
    protocol: TCP
    targetPort: {{ .Values.service.port | default 8444 }}
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    remote-desktop-user: {{ .Release.Name }}
  type: ClusterIP
