apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-vnc
spec:
  ports:
  - port: {{ .Values.service.port | default 8444 }}
    protocol: TCP
    targetPort: {{ .Values.service.port | default 8444 }}
  selector:
    remote-desktop-user: {{ .Release.Name }}
  type: ClusterIP