apiVersion: tekton.dev/v1
kind: Task
metadata:
  annotations:
    artifacthub.io/category: integration-delivery
    artifacthub.io/maintainers: |
      - name: KubeVirt Tekton tasks maintainers
        email: kubevirt-tekton-tasks@redhat.com
    artifacthub.io/provider: KubeVirt
    artifacthub.io/recommendations: |
      - url: https://kubevirt.io/
    tekton.dev/categories: Automation
    tekton.dev/displayName: KubeVirt cleanup VM
    tekton.dev/pipelines.minVersion: 0.43.0
    tekton.dev/platforms: linux/amd64,linux/s390x,linux/arm64
    tekton.dev/tags: kubevirt
  labels:
    app.kubernetes.io/version: v0.24.0
  name: cleanup-vm
  namespace: vm-pipelines
spec:
  description: Run commands in KubeVirt virtual machine. This task can stop and delete
    VMs
  params:
  - description: Name of a VM to execute the action in.
    name: vmName
    type: string
  - default: ""
    description: Namespace of a VM to execute the action in. (defaults to active namespace)
    name: vmNamespace
    type: string
  - default: "true"
    description: Stops the VM after executing the commands when set to true.
    name: stop
    type: string
  - default: "false"
    description: Deletes the VM after executing the commands when set to true.
    name: delete
    type: string
  - default: 30m
    description: Timeout for the command/script (includes potential VM start). The
      VM will be stopped or deleted accordingly once the timout expires. Should be
      in a 3h2m1s format.
    name: timeout
    type: string
  - default: __empty__
    description: Secret to use when connecting to a VM.
    name: secretName
    type: string
  - default: []
    description: Command to execute in a VM.
    name: command
    type: array
  - default: []
    description: Arguments of a command.
    name: args
    type: array
  - default: ""
    description: Script to execute in a VM.
    name: script
    type: string
  steps:
  - args:
    - --stop
    - $(params.stop)
    - --delete
    - $(params.delete)
    - --timeout
    - $(params.timeout)
    - --
    - $(params.command)
    - $(params.args)
    command:
    - entrypoint
    computeResources: {}
    env:
    - name: COMMAND
      value: execute-in-vm
    - name: VM_NAME
      value: $(params.vmName)
    - name: VM_NAMESPACE
      value: $(params.vmNamespace)
    - name: EXECUTE_SCRIPT
      value: $(params.script)
    - name: CONNECTION_SECRET_NAME
      value: $(params.secretName)
    image: quay.io/kubevirt/tekton-tasks:v0.24.0
    name: execute-in-vm
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    volumeMounts:
    - mountPath: /data/connectionsecret/
      name: connectionsecret
      readOnly: true
  volumes:
  - name: connectionsecret
    secret:
      optional: true
      secretName: $(params.secretName)
