apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: generate-password
  namespace: vm-pipelines
spec:
  description: Generates a password
  params:
  - default: "8"
    description: The user emial address
    name: PASSWORD_LENGTH
    type: string
  - default: A-Za-z0-9
    description: Characters filter
    name: CHAR_FILTER
    type: string
  - default: quay.io/fedora/fedora:42
    description: OS image to be used
    name: OS_IMAGE
    type: string
  results:
  - description: |
      Generated password string
    name: generated-password
    type: string
  steps:
  - computeResources: {}
    image: $(params.OS_IMAGE)
    name: generate-password
    script: |
      #!/usr/bin/env bash

      GENERATED_PASSWORD=$(tr -dc $(params.CHAR_FILTER) < /dev/urandom | head -c $(params.PASSWORD_LENGTH))
      echo "Generated password is: ${GENERATED_PASSWORD}"
      printf "%s" "${GENERATED_PASSWORD}" > "$(results.generated-password.path)"
