apiVersion: tekton.dev/v1
kind: Task
metadata:
  annotations:
    openshift.io/installed-from: Tektonhub
    tekton.dev/categories: Deployment
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/platforms: linux/amd64,linux/s390x,linux/ppc64le,linux/arm64
    tekton.dev/tags: helm
  labels:
    app.kubernetes.io/version: "0.3"
  name: helm-upgrade-from-repo
  namespace: vm-pipelines
spec:
  description: These tasks will install / upgrade a helm chart into your Kubernetes
    / OpenShift Cluster using Helm
  params:
  - description: Specify a specific helm repo
    name: helm_repo
    type: string
  - description: Specify chart name that will be deployed
    name: chart_name
    type: string
  - default: v1.0.0
    description: The helm release version in semantic versioning format
    name: release_version
    type: string
  - default: helm-release
    description: The helm release name
    name: release_name
    type: string
  - default: ""
    description: The helm release namespace
    name: release_namespace
    type: string
  - default: ""
    description: 'Specify the values you want to overwrite, comma separated: autoscaling.enabled=true,replicas=1'
    name: overwrite_values
    type: string
  - default: docker.io/lachlanevenson/k8s-helm@sha256:0a068ae407e21d1836c6a89a1e9e81af1e55fa56890998e33d5caabdbb51e77b
    description: Specify a specific helm image
    name: helm_image
    type: string
  steps:
  - computeResources: {}
    image: $(params.helm_image)
    name: upgrade-from-repo
    script: |
      echo current installed helm releases
      helm list --namespace "$(params.release_namespace)"
      echo parsing helms repo name...
      REPO=`echo "$(params.chart_name)" | cut -d "/" -f 1`
      echo adding helm repo...
      helm repo add $REPO "$(params.helm_repo)"
      echo adding updating repo...
      helm repo update
      echo installing helm chart...
      helm upgrade --install --namespace "$(params.release_namespace)" $(params.release_name) $(params.chart_name) --debug --set "$(params.overwrite_values)"
