apiVersion: tekton.dev/v1
kind: Task
metadata:
  annotations:
    tekton.dev/categories: Messaging
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/platforms: linux/amd64,linux/s390x,linux/ppc64le
    tekton.dev/tags: messaging
  labels:
    app.kubernetes.io/version: "0.1"
  name: send-to-telegram
  namespace: vm-pipelines
spec:
  description: |-
    These tasks post a simple message to a telegram chat.
    This task uses the Bot API of telegram to send a message.
  params:
  - description: Token of the bot through
    name: bot-token-secret
    type: string
  - description: ID of the chat to send the message towards
    name: chat-id
    type: string
  - description: The message to notify about
    name: message
    type: string
  steps:
  - computeResources: {}
    env:
    - name: BOT_TOKEN
      valueFrom:
        secretKeyRef:
          key: token
          name: $(params.bot-token-secret)
    - name: CHAT_ID
      value: $(params.chat-id)
    - name: MESSAGE
      value: $(params.message)
    image: docker.io/curlimages/curl:7.70.0@sha256:031df77a11e5edded840bc761a845eab6e3c2edee22669fb8ad6d59484b6a1c4
    name: post
    script: |
      #!/bin/sh
      MESSAGE=`echo $MESSAGE | sed -e 's/\"/\\\\"/g'`
      JSON="{\"chat_id\": ${CHAT_ID}, \"text\": \"${MESSAGE}\" }"
      curl -X POST -H 'Content-Type: application/json' -d "${JSON}" https://api.telegram.org/bot${BOT_TOKEN}/sendMessage
