apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: virtctl-cli
  namespace: vm-pipelines
spec:
  description: Provides virtctl CLI
  params:
  - description: The Arguments to be passed to virtctl command.
    name: ARGS
    type: string
  - default: quay.io/linuxeroagrio/virtctl:4.19
    description: Virtctl image to be used
    name: VIRTCTL_IMAGE
    type: string
  steps:
  - computeResources: {}
    image: $(params.VIRTCTL_IMAGE)
    name: virtctl-cli
    script: |
      #!/usr/bin/env bash
      virtctl $(params.ARGS)
    workingDir: $(workspaces.objects.path)
  workspaces:
  - name: objects
    optional: true
