apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: virtual-desktop-source-code
  namespace: vm-pipelines
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
