apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: virtual-desktop-dev-disk-image
  namespace: vm-pipelines
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi
