apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: virtual-desktop-generated-user-vm-iso
  namespace: vm-pipelines
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi
