apiVersion: v1
stringData:
  .dockerconfigjson: <PUT_YOUR_REGISTRY_CREDENTIALS_CONFIG_JSON_HERE>
kind: Secret
metadata:
  name: skopeo-creds
  namespace: vm-pipelines
type: kubernetes.io/dockerconfigjson
