# Virtual machine configuration
virtualMachineResources:
  runStrategy: Halted #https://kubevirt.io/user-guide/compute/run_strategies/
  memory: 4Gi
  cpu: "2"
  cdrom:
    tray: closed

# Exposed Service Port
service:
  port: 8444

# Disks configuration
storage:
  rootdisk:
    capacity: "30Gi"
    accessMode: ReadWriteOnce
    storageClass: lvms-vg1
  homedisk:
    capacity: "30Gi"
    accessMode: ReadWriteOnce
    storageClass: lvms-vg1