apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: docker.io/guacamole/guacamole:latest
        name: guacamole
        ports:
        - containerPort: 8080
          name: web
          protocol: TCP