apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vm-pipelines

resources:
- ../../base

patches:
- path: patch-virtual-desktop-source-code-pvc.yaml
  target:
    kind: PersistentVolumeClaim
    name: virtual-desktop-source-code
- path: patch-virtual-desktop-dev-disk-image-pvc.yaml
  target:
    kind: PersistentVolumeClaim
    name: virtual-desktop-dev-disk-image
- path: patch-toml-source-code-pvc.yaml
  target:
    kind: PersistentVolumeClaim
    name: toml-source-code
- path: patch-virtual-desktop-generated-user-vm-iso-pvc.yaml
  target:
    kind: PersistentVolumeClaim
    name: virtual-desktop-generated-user-vm-iso